version: "3.7"

services:
  pagerdutycast:
    depends_on:
      - wireguard  # Removed incorrect condition, v3.7 does not support it
    image: tintindohoang/pagerdutycast:latest
    container_name: pagerdutycast-wg
    environment:
      - NAME="XYZ"  # Change this to name of the Chromecast-enabled device
      - IP="192.168.1.1"  # Change this to the IP address of the Chromecast device
      - Pagerapi="XYZ"  # Change this to the PagerDuty API key
      - User="XYZ"  # Change this to the User ID from PagerDuty
      - IPVPN="172.168.12.7"  # Change this to the VPN IP of the WireGuard node
      - Time=30  # Default value is 15, increase if needed
      - Timezone=Europe/Warsaw  # Set your timezone

    restart: unless-stopped
    network_mode: "service:wireguard"  # Ensure correct service name
    healthcheck:
      test: ["CMD", "/bin/bash", "/app/health_check.sh"]
      interval: 30s
      retries: 3
      timeout: 10s

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    networks:
      - net01
    volumes:
      - "/home/ubuntu/wg:/config"  # Path to WireGuard config
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: ["CMD-SHELL", "wg show interfaces || exit 1"]  # More reliable healthcheck
      interval: 30s
      retries: 3
      timeout: 10s

networks:
  net01:
    driver: bridge
