version: "3.7"
services:
  pagerdutycast:
    image: tintindohoang/pagerdutycast:latest
    container_name: pagerdutycast
    environment:
      - NAME=XYZ  #change this to name of the Chromecast-enabled device
      - IP=192.168.1.1 #change this to the IP address of the Chromecast-enabled device
      - Pagerapi=XYZ #change this tp the PagerDuty API key linked to your account
      - User=XYZ #change this to the User ID found in the address bar of the PagerDuty website
      - Time=30 #defualt value without this tag is 15
      - Timezone= #Add your timezone Asia/Ho_Chi_Minh or Europe/Warsaw
      - AlARMURL = #URL TO THE MP3 FILE FROM THE WEB

    restart: unless-stopped