name: Deploy to Instance


on:
  [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo su - <<EOF #start a root shell
          #install docker compose plugin.
          cd /var/lib/docker/volumes/portainer_data/_data/compose/1/
          docker compose down
          docker compose up -d
          EOF